### ISSUE TITLE
Sadles for more players

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#12]
Should staff or elders be able to use saddles? There is the issue that it can carry players away without them wanting it. It also hinders the player not using the saddle from interacting with the world in any way. There is also the fact that it obscures half of the screen.

**Comment by remiscarlet** [comment]
Tell @CirnoTheGenius to modify it so there are separate permissions for user entities versus mob entities.

**Comment by Katrix** [comment]
While that would be nice, there is also the fact that people want to make totem poles again.

**Comment by remiscarlet** [comment]
@CirnoTheGenius
