### ISSUE TITLE
Remi is a fajita

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#13]
pls fix or i get my dad to ban u he werks at nintendo and will get your club penguin account banned from xbox live

**Comment by remiscarlet** [comment]
ur banned from lyfe

**Comment by remiscarlet** [comment]
r u wna die

**Comment by CirnoTheGenius** [comment]
ye

**Comment by remiscarlet** [comment]
u r kill

**Comment by CirnoTheGenius** [comment]
no, u r gona git kil m8

**Comment by remiscarlet** [comment]
I wil kil u so hrd u wil die to deth

**Comment by remiscarlet** [comment]
Fokin skrub

**Comment by CirnoTheGenius** [comment]
Il rek u m8 Fite me

**Comment by remiscarlet** [comment]
Oi fukkboi u wot say? Fokin shank ur mum

**Comment by CirnoTheGenius** [comment]
Pls no harm MI mum m8

**Comment by remiscarlet** [comment]
U btr stop bein a fukkboi an be muh fukktoi m8y

**Comment by CirnoTheGenius** [comment]
gib mi teh nanahira moosic nd i wil

**Comment by remiscarlet** [comment]
Bitxh i have two physical albums and all of her music downloaded. Come at mi bru r u even a nanahira fan

**Comment by CirnoTheGenius** [comment]
m8 gib monis 4 teh albamns
specifically enough for versus! :^)
or voltage ignition 2 pls

**Comment by remiscarlet** [comment]
u dun ebn buy cd. u fokin skrub

**Comment by CirnoTheGenius** [comment]
m8 il rek ur fambily for dem see dees

**Comment by remiscarlet** [comment]
oi fuccboi u wnt git anywer if i hab u tied in mi basement as mi sex toi

**Comment by CirnoTheGenius** [comment]
im gona git rebase ur mom if u no gib st00f
