### ISSUE TITLE
Download for Genso 1.8, Makai, Senkai and NewHaku

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#15]
Update download for Genso 1.8, add a version of Makai with Pandæmonium, add a non broken version of Senkai and add NewHaku.

**Comment by Katrix** [comment]
@remiscarlet going to need this for RTY 2 soon.

**Comment by remiscarlet** [comment]
https://mega.nz/#F!I0thFQjS!EFEudHX2QflunhCXIuzEww

**Comment by Katrix** [comment]
The version of Genso in there is 1.7 version
