### ISSUE TITLE
Can't toggle weather in Genso

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#16]
You can't make it rain in Genso. Something with Multiverse, or something elsewhere?

**Comment by Katrix** [comment]
From what I can see, it was disabled by MV. To enable weather use /mvm set weather true.

Now for the question, we already have day and night in Genso, do we want weather as well?

In my opinion I think that we should have it as we already have day and night and it would be kind of cool.

**Comment by remiscarlet** [comment]
Do whatever you want.
