### ISSUE TITLE
Corrupted chunk + 1.8.7 clients

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#17]
There is a corrupted chunk in creative at around x:400 z:575 that kicks players entering it. From x:687 z:576 to x:352 z:911 it crashes you with the message: internal exception io.netty.handler.codec.decoderexception: java.lang.indexoutofboundsexception: readerindex(9) + lenght (1) exceeds writerindex(9): unpolledheapbytebuf(ridx: 9, widx: 9, cap: 9)

1.8.7 clients cannot connect either. Fix is same

**Comment by Katrix** [comment]
Fixed that specific area, however to fix the bug itself, we need to update to 1.8.7

**Comment by LunaPixu** [comment]
Another corrupted chunk has shown up in Creative Flats. One caused by under-the-radar griefer, ArrowBlaze. Need to check the coords and see as to where I wound up when I was crashed by him.

EDIT: Coords seem to be around -800 1400 in survival. Could be wrong though,

**Comment by Katrix** [comment]
This is fixed now
