### ISSUE TITLE
Statue world

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#18]
I don't know if who I've talked to specifically before about this, but I'm sure at least some people are aware of the statues in creative. As it stands now, we're running out of space for these statues. Can we make a seperate world just for these statues. That way we can

**Comment by remiscarlet** [comment]
Sure. Knock yourself out. You don't need me for this. Just use MV.

**Comment by Katrix** [comment]
I generally ask before making a world.

**Comment by remiscarlet** [comment]
ik. I never said you didn't have to ask me. I just said "okay, go ahead and make it".
