### ISSUE TITLE
1.8 blocks not being protectable

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#2]
See https://github.com/Hidendra/LWC/issues/883 and https://github.com/Hidendra/LWC/wiki/Bukkit-1.8. Might want to upgrade to a newer version to make sure that all new protections are made with UUID.

Might also want to consider running a build from the converter branch to update the database to UUIDs. That way all protections are at least using UUIDs.

**Comment by remiscarlet** [comment]
But we already are on build 926 though...

**Comment by Katrix** [comment]
We need to run this https://artifacts.getlwc.org/Hidendra/LWC/240/240.1/core/target/LWC.jar once to convert what is not UUIDs into UUIDs. We also need to allow 1.8 blocks to be protectable. To do that, configs needs to be updated as seen here https://github.com/Hidendra/LWC/wiki/Bukkit-1.8

**Comment by Katrix** [comment]
Oh, BTW, I don't remember if I told you, but the fixed config is in the Dropbox RTY server.

**Comment by remiscarlet** [comment]
Fixed?
