### ISSUE TITLE
Move bugs bugs.yukkuricraft.net over to new issue tracker

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#20]
I think that the new issue tracker is functioning just fine at the moment. Thus I think we should move the old bugs.yukkuricraft.net over to the new issue tracker. There are already 2 more issues there since we started this issue tracker here.

**Comment by remiscarlet** [comment]
Fixed by duplicate entry https://github.com/remiscarlet/YukkuricraftBugReports/issues/26
