### ISSUE TITLE
Switch to minecraft worldborder?

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#21]
So, I don't know why we haven't done this in the past. As it is right now, I can't really see any reason to use the Worldborder plugin. The only reason to keep it that I can think of is the circular border, which I am pretty sure will be used less and less.

**Comment by remiscarlet** [comment]
Worldborder also has other features like filling in blank space and trimming chunks outside the border. We seem to get random chunks spawning in parts beyond the border so I do an occasional cleanup. I don't plan on switching over to native borders anytime soon
