### ISSUE TITLE
Rare Painting Bug

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#25]
Submitter: MauriceJBM
Email: mauu_16guapo@hotmail.com
Hello, my issue is that one of my paintings have a repeated frame.
There's 6 maps that makes my painting complete, but two of em' are repeated by the same picture when both are different maps.
I don't know what can be but the numbers of this painting map are:
#8316 and #8315.

I really hope you bros can help me out, this happened 2 or 3 days ago more or less.
Thanks.

**Comment by CirnoTheGenius** [comment]
Can't investigate by myself, provided map IDs point to blank/vanilla maps?
