### ISSUE TITLE
Move bugs

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#26]
Submitter: Remi
Email: scarletjaeger@gmail.com
Redirect bugs.yukkuricraft CNAME to gitreports.com/issue/remiscarlet/YukkuricraftBugReports

**Comment by remiscarlet** [comment]
Fixed. Waiting for DNS servers to update.

**Comment by Katrix** [comment]
Status on this? Tried the url, and it doesn't work.

**Comment by remiscarlet** [comment]
Yeah, was looking at it last night. Something weird happened with the DNS records. Fixed it though.
