### ISSUE TITLE
Search page layout shows code and the layout itself isn't arranged

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#30]
Submitter: Kristia
Email: kristaluna@live.com.mx
As the title says, the Search page has a layout problem, it shows codes and its options overlay the page's areas

<<<<<<<< Your Customized Value <<<<<<<< ======== Old Default Value ======== =================================== >>>>>>>> New Default Value >>>>>>>>

The search page has this lines on top of the title image
https://yukkuricraft.net/search.php?...owposts=0&type[]=1

Warning: Declaration of vBForum_Item_SocialGroupMessage::getLoadQuery() should be compatible with that of vB_Model::getLoadQuery() in ..../packages/vbforum/item/socialgroupmessage.php on line 261

Warning: Declaration of vBForum_Item_SocialGroupDiscussion::getLoadQuery() should be compatible with that of vB_Model::getLoadQuery() in ..../packages/vbforum/item/socialgroupdiscussion.php on line 337

and the search page itself has parts that overlaps others.

I already had posted this bug a year and half ago by the way.

**Comment by remiscarlet** [comment]
May be fixed by resolving issue https://github.com/remiscarlet/YukkuricraftBugReports/issues/31

**Comment by CirnoTheGenius** [comment]
til that authorizing gitreports makes it post from my account. thanks.
