### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#32]
Submitter: Tewi
Email: charity_rimu@yahoo.com
To put it simply spell check is no longer working on the forums, at least not for me. Yes I did check to make sure spell check was still turned on by right clicking the chat box and looking under spell check. But even with "Check spelling of text fields" being checked and the language being set to "United States English" it still doesn't show me any spelling mistakes I've made in my posts.

**Comment by remiscarlet** [comment]
May also be related to https://github.com/remiscarlet/YukkuricraftBugReports/issues/31

Investigate further
