### ISSUE TITLE
Voxel and stuff

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#40]
Submitter: Phantom
Email: phantom-13@hotmail.com
Voxel's currently broken or at least unusable by people (possibly a permission issue based on what tenko said), and //fix lighting is slightly broken where the edges of shaded places will bug out while completely covered areas are fine.

**Comment by remiscarlet** [comment]
I'm gonna bet a pretty penny it's the fast async voxel. Removed for now. Will hopefully be fixed on restart.,
