### ISSUE TITLE
Permission check for Sakuya's World.

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#41]
Submitter: 十六夜
Currently, I am unable to interact or manipulate with my world, Sakuya's World. Blocks seem to be guarded and cannot be manipulated, while items do not stay in the inventory, forcing a clear empty inventory; so I am unable use even World Edit nor Voxel. There are also hostile and docile mobs spawning in, which if I may request to have disabled. Also, the knowledge of this world and its content is designed to be hidden until the time of its revealing. So if possible, I would like to have access to the world limited to Ojousama and myself only.

**Comment by Katrix** [comment]
Fixed perms, disabled mob spawn, set mode to creative, only staff can edit and join world(only possible to go there through /mvtp)
