### ISSUE TITLE
Changing time.

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#42]
Submitter: Redleaf64
Doing a /time set [time] in creative (As there's no playertime command yet) apparently affects survival as well. So changing time in creative will also change the time in survival.

**Comment by remiscarlet** [comment]
Something fixable by adding /playertime in swiss knife plugin?

**Comment by remiscarlet** [comment]
@CirnoTheGenius 

Resolution of this ticket would resolve part of https://github.com/remiscarlet/YukkuricraftBugReports/issues/43

**Comment by tsunko** [comment]
Need to actually do this.
Psuedo:
check args[0] for int
check args[1] for world
(args.length > 1 ? Bukkit.getWorld(args[1]) : ((Player)sender).getWorld()).setTime(Integer.parseInt(args[0]));

**Comment by Katrix** [comment]
Fix in Crux added
