### ISSUE TITLE
Survival World; Time and Weather; Playertime

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#43]
Submitter: 十六夜
I'm under the understanding that only Administrators are the only ones with the allowed capabilities of manipulating the Survival World with editing tools. With that, I am still able to change the time and weather within Survival freely. Also, in tangent with time, will the plugin Playertime be replaced or reworked?

**Comment by Katrix** [comment]
Fix in Crux added
