### ISSUE TITLE
Everything is terrible

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#44]
Submitter: TRXD
Email: officialtrxd@gmail.com
A multitude of plugins are broken.

Before I asked Tenshi to shut the server down, I noted the following plugins broke, in order of severity:

LWC
Prism
ontime 

Not sure what's what or what exactly has happened but this is awful.

**Comment by remiscarlet** [comment]
Mysql went down. Fixed. Cause was disk space. Also fixed.
