### ISSUE TITLE
Crash in gapworld

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#52]
Submitter: Spacecoreflake
Using the MC Version 1.10.1 and you teleport to the Gapworld (using the warp gapworld) the game crashes)

**Comment by Katrix** [comment]
Need for info here, crashlog would be neat. Does it happen with 1.10.2.

**Comment by tsunko** [comment]
Doesn't happen to 1.10.2, as far as I can tell.
