### ISSUE TITLE
Disappearing entities in Kagome

### ISSUE THREAD

**Issue by CirnoTheGenius** [remiscarlet/YukkuricraftBugReports#54]
Submitter: Tewi
I've noticed the item frames, paintings and armor stands in some parts of kagome seem to disappear randomly. Some places are an easy fix but places like the museum that have a a lot of map paintings and other stuff take a long time to fix. Is there a way to keep this from happening?

**Comment by Katrix** [comment]
AFAIK we already have protections set for this stuff. Could there be something we forgot here?
