### ISSUE TITLE
Inventories shared between NewHaku and Genso + permissions

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#6]
Allow inventories to be shared between Genso and NewHaku + Fix NewHaku to use same permissions as Genso. I could to that myself, but I'm  a bit unsure how it's set up as I can't see any world inheritance stuff.

**Comment by remiscarlet** [comment]
Permissions are the exact same. Every user has the same permissions across all worlds except in survival worlds which are exceptions. While we're likely to add/remove/edit around Genso related worlds, we'll rarely add new worlds to survival. Therefore, I have it set for those to be the exception. Not the standard.

**Comment by remiscarlet** [comment]
Inventories linked. Should take effect next restart.
