### ISSUE TITLE
Portal to Senkai

### ISSUE THREAD

**Issue by Katrix** [remiscarlet/YukkuricraftBugReports#8]
There needs to be a portal to Senkai. There is none at the moment.

**Comment by Katrix** [comment]
Portal created, however inventories needs to be linked and permissions are not the same. Because of this, the portal out of Senkai is currently not working.

**Comment by remiscarlet** [comment]
I've said this before and I'll say it again. If the world is explicitly not from the following list
- NeoSurvival
- NeoSurvival_the_end
- NeoSurvival_nether
- CreativeFlats

Then the permissions ARE ALL THE SAME. If the world is not from the list, then ALL PERMISSIONS DEFAULT TO GENSOKYO PERMISSIONS.

I'll add inventories when I'm not punching out my phone on a bus.

**Comment by Katrix** [comment]
Alright, I was mistaken here. Everyone told me they didn't have permission, although the problem here is something different. The issue here is that normal players for some reason can't use pressure plates. The message that appears when they try is 

"**Hey!** Sorry, but you can't use that here."

From what I can see, it's a worldguard issue. Do we have anything WG specific on Senkai?

**Comment by remiscarlet** [comment]
I believe redstone related things are disabled in Genso related worlds since that's a ModifyWorld message. I vaguely remember something about having to disable them due to potential grief

**Comment by Katrix** [comment]
As I said, its from WG. Also Redstone specific stuff is not disabled in Genso as I can make portals anywhere in Genso. It's only in Senkai it's a problem.

**Comment by remiscarlet** [comment]
Probably just haven't copied the setting file from genso, then. Senkai was a last minute throw-together like a day after we did the video cuz Nazrin pushed for it.

**Comment by remiscarlet** [comment]
https://bitbucket.org/Remi_Scarlet/yukkuricraft/issues/88/-----------------

**Comment by Katrix** [comment]
Inventories are still not linked.
